accounts_app/urls.py
from django.urls import path
from . import views

app_name = 'accounts_app'

urlpatterns = [
    path('register/', views.register, name="register"), # register
    path('login/', views.login_view, name="login"), # login
    path('logout/', views.logout_view, name='logout'), # Logout
    path('user/', views.user_profile, name='user_profile'), # For user_profiles
    path('Terms/', views.Terms, name="Terms"), # Terms and conditions
]

del_app/urls.py
from django.urls import path
from .import views

app_name = 'del_app'

urlpatterns = [
    path('',views.home,name='home'),# Home section 
    path('about/',views.about,name='about'),# About section 
    path('menu/',views.menu,name='menu'),# Menu section 
    path('events/',views.events,name='events'),# Events section
    path('gallery/',views.gallery,name='gallery'),# Gallery section 
    path('contact/',views.contact,name='contact'),# For the contact section
    path('show_contacts/',views.contact_info, name="show_contacts"), # For contact information
    path('edit_contact/<int:contact_id>/', views.update_contact, name='update_contact'), # For any contact information edits
    path('delete_contact/<int:id>/', views.delete_contact, name='delete_contact'), # For any details that entai contact info deletions
    path('book_table/',views.booking_table, name="book_table"), # For Table bookings
    path('show_bookings/', views.show_bookings, name="show_bookings"), # For showing Bookings update
    path('delete/<int:id>/', views.delete_booking, name= 'delete_booking'), # For any booking deletions
    path('edit/<int:booking_id>/', views.update_booking, name="edit_booking"), # For any Booking updates

    # Urls used in togetherness with the mpesa api
    path('pay/', views.pay, name='pay'), # The view for the payment form
    path('stk/', views.stk, name='stk'), # Its function is to send the stk push prompt
    path('token/', views.token, name='token'), # generates a token for any particular transaction that takes place
]

proj_licious/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('del_app.urls')),
    path('accounts/',include('accounts_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}

{% if messages %}
<ul>
  {% for message in messages %}
  <h6 class="{% if message.tags == 'error' %} red {% else %} alert alert-warning mt-3 {% endif %}; background-color: {% if message.tags == 'error' %} white {% else %} white {% endif %};">
    {{ message }}
  </h6>
  {% endfor %}
</ul>
{% endif %}

<!-- Login section start -->
<section class="bg-light p-3 p-md-4 p-xl-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-xxl-11">
                <div class="card border-light-subtle shadow-sm">
                    <div class="row g-0">
                        <div class="col-12 col-md-6">
                            <img class="img-fluid rounded-start w-100 h-100 object-fit-cover" loading="lazy" 
                                 src="{% static 'assets/img/register-1.jpg' %}" alt="Welcome back!">
                        </div>
                        <div class="col-12 col-md-6 d-flex align-items-center justify-content-center">
                            <div class="col-12 col-lg-11 col-xl-10">
                                <div class="card-body p-3 p-md-4 p-xl-5">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="mb-5">
                                                <div class="text-center mb-4"></div>
                                                <h2 class="h1 text-center">Login</h2>
                                                <p>Login to manage your reservations</p>
                                            </div>
                                        </div>
                                    </div>
                                    <form method="POST">
                                        {% csrf_token %}
                                        <div class="row gy-3 overflow-hidden">
                                            <div class="col-12">
                                                <div class="form-floating mb-3">
                                                    <input type="text" class="form-control" name="username" id="username" placeholder="Username" required value="{{ username|default:'' }}">
                                                    <label for="username" class="form-label">Username</label>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-floating mb-3">
                                                    <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
                                                    <label for="password" class="form-label">Password</label>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="form-check">
                                                    <input class="form-check-input" type="checkbox" value="" name="rememberPassword" id="rememberPassword" required>
                                                    <label class="form-check-label text-secondary" for="rememberPassword">Remember password</label>
                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <div class="d-grid">
                                                    <button class="btn btn-dark btn-lg" type="submit">Login</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                    <div class="row">
                                        <div class="col-12">
                                            <p class="mb-0 mt-5 text-secondary text-center">
                                                Don't have an account? 
                                                <a href="{% url 'accounts_app:register' %}" class="link-primary text-decoration-none">Register here</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Login section ends -->
{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}Register{% endblock %}
{% block content %}

{% if messages %}
<ul>
  {% for message in messages %}
  <h6 class="{% if message.tags == 'error' %} red {% else %} alert alert-warning mt-3 {% endif %}; background-color: {% if message.tags == 'error' %} white {% else %} white {% endif %};">
    {{ message }}
  </h6>
  {% endfor %}
</ul>
{% endif %}

<!-- Registration section start -->
<section class="bg-light p-3 p-md-4 p-xl-5">
    <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-xxl-11">
        <div class="card border-light-subtle shadow-sm">
          <div class="row g-0">
            <div class="col-12 col-md-6">
              <img class="img-fluid rounded-start w-100 h-100 object-fit-cover" loading="lazy" src="{% static 'assets/img/register-1.jpg'%}" alt="Welcome back you've been missed!">
            </div>
            <div class="col-12 col-md-6 d-flex align-items-center justify-content-center">
              <div class="col-12 col-lg-11 col-xl-10">
                <div class="card-body p-3 p-md-4 p-xl-5">
                  <div class="row">
                    <div class="col-12">
                      <div class="mb-5">
                        <div class="text-center mb-4">                          
                        </div>
                        <h2 class="h1 text-center">Registration</h2>
                      </div>
                    </div>
                  </div>
                  <div class="row">                    
                  </div>
                  <form method="POST">
                    {% csrf_token %}
                  <div class="row gy-3 overflow-hidden">
                    <div class="col-12">
                      <p>Sign up to enjoy and order your meal</p>
                      <div class="form-floating mb-3">
                          <input name="firstName" class="form-control" type="text" id="firstName" placeholder="First Name" required value="{{ first_name|default:'' }}">
                          <label for="firstName" class="form-label">First Name</label>
                        </div>
                      </div>
                      <div class="col-12">
                        <div class="form-floating mb-3">
                          <input name="lastName" class="form-control" type="text" id="lastName" placeholder="First Name" required value="{{ last_name|default:'' }}">
                          <label for="lastName" class="form-label">Last Name</label>
                        </div>
                      </div>
                      <div class="col-12">
                        <div class="form-floating mb-3">
                          <input name="Username" class="form-control" type="text" id="Username" placeholder="Username" required value="{{ username|default:'' }}">
                          <label for="Username" class="form-label">Username</label>
                        </div>
                      </div>
                      <div class="col-12">
                        <div class="form-floating mb-3">
                          <input name="email" class="form-control" type="email" id="email" placeholder="name@example.com" required value="{{ email|default:'' }}">
                          <label for="email" class="form-label">Email</label>
                        </div>
                      </div>
                      <div class="col-12">
                        <div class="form-floating mb-3">
                          <input name="password" class="form-control" type="password" id="password" placeholder="Password" required>
                          <label for="password" class="form-label">Password</label>
                        </div>
                        <div class="form-floating mb-3">
                          <input name="confirm_password" class="form-control" type="password" id="confirm_password" placeholder="Confirm Password" required>
                          <label for="confirm_password" class="form-label">Confirm Password</label>
                        </div>
                      </div>
                      <div class="col-12">
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" value="" name="iAgree" id="iAgree" required>
                          <label class="form-check-label text-secondary" for="iAgree">
                            I agree to the <a href="{% url 'accounts_app:Terms'%}" class="link-primary text-decoration-none" required>terms and conditions</a>
                          </label>
                        </div>
                      </div>
                      <div class="col-12">
                        <div class="d-grid">
                          <button class="btn btn-dark btn-lg" type="submit">Register</button>
                        </div>
                      </div>
                    </div>
                  </form>
                  <div class="row">
                    <div class="col-12">
                        <p class="mb-0 mt-5 text-secondary text-center">Already have an account? <a href="{% url 'accounts_app:login'%}" class="link-primary text-decoration-none">Login</a></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Registration section ends -->
{% endblock %}

templates/accounts/terms.html
{% extends "base.html" %}
{% block title %}Terms and conditions {% endblock %}
{% block content %}
<!-- Terms Section -->
<section id="Terms and conditions" class="Terms and conditions section">

   <!-- Section Title -->
   <div class="container section-title" data-aos="fade-up">
     <h2>Terms and conditions </h2>
     <div><span>DineReserve </span> <span class="description-title">Terms and Conditions</span></div>
   </div>
   
</section>
<!-- End Section Title -->
<h1>DineReserve Terms and Conditions</h1> 
<h2>1. Introduction</h2>
 <p>Welcome to DineReserve. These Terms and Conditions govern your use of our website and services. By accessing or using our site, you agree to comply with these terms. If you do not agree, please refrain from using our services.</p>
<h2>2. Reservations</h2> 
<h3>2.1 Booking</h3> 
<p>All reservations made through DineReserve are subject to availability and confirmation. We reserve the right to cancel or amend reservations due to unforeseen circumstances.</p>
<h3>2.2 Special Requests</h3> 
<p>While we strive to accommodate special requests, we cannot guarantee they will be met.</p> 
<h2>3. User Accounts</h2> 
<h3>3.1 Account Creation</h3> 
<p>To make a reservation, users may need to create an account. You agree to provide accurate and up-to-date information during the registration process.</p> 
<h3>3.2 Account Security</h3> 
<p>You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account.</p> 
<h2>4. Payment</h2> 
<h3>4.1 Pricing</h3> 
<p>All prices are displayed in the local currency and are subject to change without notice. Prices may include applicable taxes.</p>
<h3>4.2 Payment Methods</h3>
<p>We accept various payment methods as specified on our website. Payments are processed securely through trusted third-party payment processors.</p>
<h2>5. Cancellations and Refunds</h2>
<h3>5.1 Cancellation Policy</h3> 
<p>Cancellations must be made in accordance with our cancellation policy. Failure to comply may result in charges.</p> 
<h3>5.2 Refunds</h3> 
<p>Refunds are processed based on our refund policy, which is subject to the terms and conditions of the reservation.</p> 
<h2>6. Privacy</h2> 
<h3>6.1 Data Collection</h3> 
<p>We collect and use personal data in accordance with our Privacy Policy. By using our services, you consent to such data practices.</p> 
<h3>6.2 Data Protection</h3> 
<p>We implement appropriate security measures to protect your personal information from unauthorized access or disclosure.</p> 
<h2>7. User Conduct</h2> 
<h3>7.1 Acceptable Use</h3> 
<p>You agree to use our services for lawful purposes only and not to engage in any activity that may harm or disrupt our operations.</p> 
<h3>7.2 Prohibited Actions</h3> 
<p>Prohibited actions include, but are not limited to, unauthorized access, data breaches, and fraudulent activities.</p> 
<h2>8. Intellectual Property</h2> 
<h3>8.1 Ownership</h3> 
<p>All content on our website, including text, graphics, logos, and images, is the property of DineReserve and is protected by intellectual property laws.</p> 
<h3>8.2 Usage</h3> 
<p>You may not reproduce, distribute, or create derivative works from our content without prior written consent.</p> 
<h2>9. Limitation of Liability</h2> 
<h3>9.1 Disclaimer</h3> 
<p>DineReserve is not liable for any direct, indirect, incidental, or consequential damages arising from the use or inability to use our services.</p> 
<h3>9.2 Indemnification</h3> 
<p>You agree to indemnify and hold DineReserve harmless from any claims, damages, or expenses arising from your use of our services.</p> 
<h2>10. Changes to Terms</h2> 
<h3>10.1 Modifications</h3> 
<p>DineReserve reserves the right to amend these Terms and Conditions at any time. Changes will be posted on our website and will take effect immediately upon posting.</p> 
<h2>11. Governing Law</h2> 
<h3>11.1 Jurisdiction</h3> 
<p>These Terms and Conditions are governed by and construed in accordance with the laws of Kenya. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts in Kenya.</p> 
<h2>12. Contact Us</h2> 
<p>If you have any questions or concerns about these Terms and Conditions, please contact us at:</p>
 <ul>
    <li><strong>Email:</strong>
         <a href="mailto:info@DineReserve.com">info@DineReserve.com</a>
    </li> <li><strong>Phone:</strong> +254 745804539</li>
 </ul>
{% endblock %}

templates/accounts/user_profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block content %}
{% if messages %}
<ul>
  {% for message in messages %}
  <h6 class="{% if message.tags == 'error' %} red {% else %} alert alert-warning mt-3 {% endif %}; background-color: {% if message.tags == 'error' %} white {% else %} white {% endif %};">
    {{ message }}
  </h6>
  {% endfor %}
</ul>
{% endif %}
<!-- Profile_editing Section -->
<section id="Update" class="update section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
      <h2>Update</h2>
      <div><span>Update your </span> <span class="description-title">Credentials</span></div>
    </div>
    
</section>
<!-- End Section Title -->

<div class="container mt-3">
    <!-- Username Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h2>{{ user.username }}</h2>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-lg-4 pb-5">
            <!-- Account Sidebar-->
            <div class="author-card pb-3">
                <div class="author-card-cover" style="background-image: url('{% static 'images/default_profile_picture.png' %}');"></div>
                <div class="author-card-profile">
                    <div class="text-center">
                        <img src="{{ profile_picture }}" class="avatar img-circle img-thumbnail" alt="avatar">
                        <h6>Upload your photo...</h6>
                    </div>
                </div>
            </div>
            <div class="wizard">
                <nav class="list-group list-group-flush">
                    <a class="list-group-item" href="#"></a>
                    <a class="list-group-item" href="#"></a>
                    <a class="list-group-item" href="#"></a>
                </nav>
            </div>
        </div>
        <!-- Profile Settings-->
        <div class="col-lg-8 pb-5">
            <form method="post" enctype="multipart/form-data" class="row" id="profileForm">
                {% csrf_token %}
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="account-fn">First Name</label>
                        <input class="form-control" type="text" id="account-fn" name="first_name" placeholder="First Name" required="" value="{{ first_name }}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="account-ln">Last Name</label>
                        <input class="form-control" type="text" id="account-ln" name="last_name" placeholder="Last Name" required="" value="{{ last_name }}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="account-email">E-mail Address</label>
                        <input class="form-control" type="email" id="account-email" name="email" placeholder="example@gmail.com" value="{{ email }}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="account-phone">Phone Number</label>
                        <input class="form-control" type="text" id="account-phone" name="phone" placeholder="Phone Number" required="" value="{{ phone }}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="account-dob">Date of Birth</label>
                        <input class="form-control" type="date" id="account-dob" name="date_of_birth" value="{{ date_of_birth|date:'Y-m-d' }}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="account-location">Location</label>
                        <input class="form-control" type="text" id="account-location" name="location" placeholder="Location" value="{{ location }}">
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="profile-picture">Profile Picture</label>
                        <input type="file" name="profile_picture" id="profile-picture" class="form-control">
                    </div>
                </div>
                <div class="col-12">
                    <hr class="mt-2 mb-3">
                    <div class="d-flex flex-wrap justify-content-between align-items-center">                        
                        <button class="btn btn-dark btn" type="submit">Save</button>
                        <button class="btn btn" type="button" id="resetButton">Reset</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
document.getElementById("resetButton").addEventListener("click", function() {
    const resetOptions = prompt("Enter 1 to reset the entire form, or 2 to reset the personal details section only:");

    if (resetOptions === "1") {
        if (confirm("Are you sure you want to reset all the contents of the page?")) {
            document.getElementById("profileForm").reset();
        }
    } else if (resetOptions === "2") {
        if (confirm("Are you sure you want to reset the personal details section only?")) {
            resetPersonalDetails();
        }
    }
});

function resetPersonalDetails() {
    document.getElementById("account-fn").value = "";
    document.getElementById("account-ln").value = "";
    document.getElementById("account-email").value = "";
    document.getElementById("account-phone").value = "";
    document.getElementById("account-dob").value = "";
    document.getElementById("account-location").value = "";
}
</script>
{% endblock %}