accounts_app/urls.py
from django.urls import path
from . import views

app_name = 'accounts_app'

urlpatterns = [
    path('register/', views.register, name="register"), # register
    path('login/', views.login_view, name="login"), # login
    path('logout/', views.logout_view, name='logout'), # Logout
    path('user/', views.user_profile, name='user_profile'), # For user_profiles
    path('Terms/', views.Terms, name="Terms"), # Terms and conditions
]

del_app/urls.py
from django.urls import path
from .import views

app_name = 'del_app'

urlpatterns = [
    path('',views.home,name='home'),# Home section 
    path('about/',views.about,name='about'),# About section 
    path('menu/',views.menu,name='menu'),# Menu section 
    path('events/',views.events,name='events'),# Events section
    path('gallery/',views.gallery,name='gallery'),# Gallery section 
    path('contact/',views.contact,name='contact'),# For the contact section
    path('show_contacts/',views.contact_info, name="show_contacts"), # For contact information
    path('edit_contact/<int:contact_id>/', views.update_contact, name='update_contact'), # For any contact information edits
    path('delete_contact/<int:id>/', views.delete_contact, name='delete_contact'), # For any details that entai contact info deletions
    path('book_table/',views.booking_table, name="book_table"), # For Table bookings
    path('show_bookings/', views.show_bookings, name="show_bookings"), # For showing Bookings update
    path('delete/<int:id>/', views.delete_booking, name= 'delete_booking'), # For any booking deletions
    path('edit/<int:booking_id>/', views.update_booking, name="edit_booking"), # For any Booking updates

    # Urls used in togetherness with the mpesa api
    path('pay/', views.pay, name='pay'), # The view for the payment form
    path('stk/', views.stk, name='stk'), # Its function is to send the stk push prompt
    path('token/', views.token, name='token'), # generates a token for any particular transaction that takes place
]

proj_licious/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('del_app.urls')),
    path('accounts/',include('accounts_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>{% block title  %}{% endblock %}</title>
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicon -->
  <link href="{% static 'assets/img/favicon.ico'%}" rel="icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Satisfy:wght@400&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'assets/css/main.css'%}" rel="stylesheet">

</head>

<body class="index-page">
  {% include "header.html" %}

  <main class="main">

   {% block content %}{% endblock %}

  </main>

  {% include "footer.html" %}

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js'%}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js'%}"></script>
  <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js'%}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js'%}"></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js'%}"></script>

</body>

</html>

templates/book_table.html
{% extends "base.html" %}
{% load static %}
{% block title %}Book_table{% endblock %}
{% block content %}

<!-- Book A Table Section -->
<section id="book-a-table" class="book-a-table section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
      <h2>Book A Table</h2>
      <div><span>Book a</span> <span class="description-title">Table with us</span></div>
    </div><!-- End Section Title -->

    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <div class="row gy-4">
              <div class="col-lg-4 col-md-6">
                <label for="name">Your Name</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" 
                       {% if user.is_superuser %}
                       value=""
                       {% else %}
                       value="{{ user.first_name }} {{ user.last_name }}" readonly
                       {% endif %}>
              </div>
              <div class="col-lg-4 col-md-6">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="example@gmail.com" 
                       {% if user.is_superuser %}
                       value=""
                       {% else %}
                       value="{{ user.email }}" readonly
                       {% endif %}>
              </div>
              <div class="col-lg-4 col-md-6">
                <label for="phone">Phone</label>
                <input type="text" class="form-control" name="phone" id="phone" placeholder="Your Phone">                       
              </div>
              <div class="col-lg-4 col-md-6">
                <label for="date">Date</label>
                <input type="date" name="date" class="form-control" id="date" placeholder="Date" required>
              </div>
              <div class="col-lg-4 col-md-6">
                <label for="time">Time</label>
                <input type="time" class="form-control" name="time" id="time" placeholder="Time" required>
              </div>
              <div class="col-lg-4 col-md-6">
                <label for="people">Number of People</label>
                <input type="number" class="form-control" name="people" id="people" placeholder="# of people" required>
              </div>
            </div>

            <div class="form-group mt-3">
              <label for="message">Message</label>
              <textarea class="form-control" name="message" id="message" rows="5" placeholder="Message"></textarea>
            </div>

            <div class="text-center mt-3">
                <p>Book a table with us</p>
                <button type="submit" class="btn btn-dark btn-lg">Book a Table</button>
            </div>
          </form>
        </div>
        <!-- End Reservation Form -->

      </div>

    </div>

</section>
<!-- /Book A Table Section -->

{% endblock %}

templates/contact.html
{% extends "base.html" %}
{% block title %}Contact{% endblock %}
{% block content %}
<!-- Contact Section -->
<section id="contact" class="contact section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
      <h2>Contact</h2>
      <div><span>Check Our</span> <span class="description-title">Contact</span></div>
    </div>
    <!-- End Section Title -->

    <div class="container" data-aos="fade">

      <div class="row gy-5 gx-lg-5">

        <div class="col-lg-4">

          <div class="info">
            <h3>Get in touch</h3>
            <p>We’d love to hear from you! Reach out to us with any questions or feedback.</p>

            <div class="info-item d-flex">
              <i class="bi bi-geo-alt flex-shrink-0"></i>
              <div>
                <h4>Location:</h4>
                <p>Street 108, Nairobi City, NC 00100</p>
              </div>
            </div><!-- End Info Item -->

            <div class="info-item d-flex">
              <i class="bi bi-envelope flex-shrink-0"></i>
              <div>
                <h4>Email:</h4>
                <p>info@DineReserve.com</p>
              </div>
            </div>
            <!-- End Info Item -->

            <div class="info-item d-flex">
              <i class="bi bi-phone flex-shrink-0"></i>
              <div>
                <h4>Call:</h4>
                <p>+254 745804539</p>
              </div>
            </div>
            <!-- End Info Item -->

          </div>

        </div>

        <div class="col-lg-8">
          <form method="post" role="form">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6 form-group">
                <label for="name">Your Name</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" value="{{ user.first_name }} {{ user.last_name }}" 
                {% if not user.is_superuser %}readonly{% endif %} required>
              </div>
              <div class="col-md-6 form-group mt-3 mt-md-0">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="example@gmail.com" value="{{ user.email }}" required>
              </div>
            </div>
            <div class="form-group mt-3">
              <label for="subject">Subject</label>
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
            </div>
            <div class="form-group mt-3">
              <label for="message">Message</label>
              <textarea class="form-control" name="message" id="message" placeholder="Message" required></textarea>
            </div>
            <div class="my-3">
              <div class="text-center mt-3">Click on the button to send your details</div>
            </div>
            <div class="text-center"><button type="submit" class="btn btn-dark btn-lg">Send Message</button></div>
          </form>
        </div>
        <!-- End Contact Form -->

      </div>

    </div>

  </section>
  <!-- /Contact Section -->

{% endblock %}

templates/edit_booking.html
{% extends "base.html" %}
{% load static %}
{% block title %}Edit_booking{% endblock %}
{% block content %}

<!-- Book A Table Section -->
<section id="edit_booking" class="edit_booking">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
      <h2>edit_booking</h2>
      <div><span>edit your </span> <span class="description-title">Bookings </span></div>
    </div><!-- End Section Title -->

    <div class="container">      
          <form method="POST">
            {% csrf_token %}
            <div class="row gy-4">
              <div class="col-lg-4 col-md-6">
                <label for="name">Your Name</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" value="{{ booking.name }}" required="">
              </div>
              <div class="col-lg-4 col-md-6">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="example@gmail.com" value="{{ booking.email }}" required="">
              </div>
              <div class="col-lg-4 col-md-6">
                <label for="phone">Phone</label>
                <input type="text" class="form-control" name="phone" id="phone" placeholder="Your Phone" value="{{ booking.phone }}" required="">
              </div>
              <div class="col-lg-4 col-md-6">
                <label for="date">Date</label>
                <input type="date" name="date" class="form-control" id="date" placeholder="Date" value="{{ booking.date|date:'Y-m-d' }}" required="">
              </div>
              <div class="col-lg-4 col-md-6">
                <label for="time">Time</label>
                <input type="time" class="form-control" name="time" id="time" placeholder="Time" value="{{ booking.time|time:'H:i' }}" required="">
              </div>
              <div class="col-lg-4 col-md-6">
                <label for="people">Number of People</label>
                <input type="number" class="form-control" name="people" id="people" placeholder="# of people" value="{{ booking.people }}" required="">
              </div>
            </div>

            <div class="form-group mt-3">
              <label for="message">Message</label>
              <textarea class="form-control" name="message" id="message" rows="5" placeholder="Message">{{ booking.message }}</textarea>
            </div>

            <div class="text-center mt-3">
                <p>Edit your bookings </p>
                <button type="submit" class="btn btn-dark btn-lg">Update Bookings</button>
            </div>
          </form>
        </div>
        <!-- End Reservation Form -->

      </div>

    </div>

  </section>
  <!-- /Book A Table Section -->

{% endblock %}

templates/edit_contact.html
{% extends "base.html" %}
{% block title %} Edit Contact{% endblock %}
{% block content %}
<!-- Contact Section -->
<section id="edit contact" class="edit contact section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
      <h2>Edit Contact</h2>
      <div><span>Edit </span> <span class="description-title">Contact info</span></div>
    </div>
    <!-- End Section Title -->

    <div class="container" data-aos="fade">

      <div class="row gy-5 gx-lg-5">

        <div class="col-lg-4">

          <div class="info">
            <h3>Get in touch</h3>
            <p>We’d love to hear from you! Reach out to us with any questions or feedback.</p>

            <div class="info-item d-flex">
              <i class="bi bi-geo-alt flex-shrink-0"></i>
              <div>
                <h4>Location:</h4>
                <p>Street 108, Nairobi City, NC 00100</p>
              </div>
            </div><!-- End Info Item -->

            <div class="info-item d-flex">
              <i class="bi bi-envelope flex-shrink-0"></i>
              <div>
                <h4>Email:</h4>
                <p>info@DineReserve.com</p>
              </div>
            </div>
            <!-- End Info Item -->

            <div class="info-item d-flex">
              <i class="bi bi-phone flex-shrink-0"></i>
              <div>
                <h4>Call:</h4>
                <p>+254 745804539</p>
              </div>
            </div>
            <!-- End Info Item -->

          </div>

        </div>

        <div class="col-lg-8">
          <form method="post" role="form">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6 form-group">
                <label for="name">Your Name</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" value="{{ contact.name }}" required="">
              </div>
              <div class="col-md-6 form-group mt-3 mt-md-0">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="example@gmail.com" value="{{ contact.email }}" required="">
              </div>
            </div>
            <div class="form-group mt-3">
              <label for="subject">Subject</label>
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" value="{{ contact.subject }}" required="">
            </div>
            <div class="form-group mt-3">
              <label for="message">Message</label>
              <textarea class="form-control" name="message" id="message" placeholder="Message" required="">{{ contact.message }}</textarea>
            </div>
            <div class="my-3">
              <div class="text-center mt-3">Click on the button to send your details</div>
            </div>
            <div class="text-center"><button type="submit" class="btn btn-dark btn-lg">Send Message</button></div>
          </form>
        </div>
        <!-- End Contact Form -->

      </div>

    </div>

  </section>
  <!-- /Contact Section -->

{% endblock %}

templates/footer.html
<footer id="footer" class="footer dark-background">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-geo-alt icon"></i>
          <div class="address">
            <h4>Address</h4>
            <p>Street 108</p>
            <p>Nairobi city </p>
            <p></p>
          </div>

        </div>

        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-telephone icon"></i>
          <div>
            <h4>Contact</h4>
            <p>
              <strong>Phone:</strong> <span>+245 745804539</span><br>
              <strong>Email:</strong> <span>info@dinereserve.com</span><br>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Opening Hours</h4>
            <p>
              <strong>Mon-Sat:</strong> <span>11AM - 23PM</span><br>
              <strong>Sunday</strong>: <span>Closed</span>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6">
          <h4>Follow Us</h4>
          <div class="social-links d-flex">
            <a href="#" class="twitter"><i class="bi bi-twitter-x"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">DineReserve</strong> <span>All Rights Reserved</span></p>
      <div class="credits">
        Designed by <a href="#">Enock Bosire </a>
      </div>
    </div>

</footer>

templates/header.html
{% load static %}
<header id="header" class="header fixed-top">

  <div class="topbar d-flex align-items-center">
    <div class="container d-flex justify-content-between">
      <div class="logo d-flex align-items-center">
        <a href="{% url 'del_app:home' %}">
          {% comment %} <img src="{% static 'assets/img/Logo.jpeg' %}" alt="Logo" class="topbar-logo"> {% endcomment %}
        </a>
      </div>
      <div class="auth-buttons">
        {% if user.is_authenticated %}
          <a href="{% url 'accounts_app:user_profile' %}" class="custom-btn me-2">Dashboard</a>
          <a href="{% url 'accounts_app:logout' %}" class="custom-btn" onclick="return confirmLogout()">Logout</a>
        {% else %}
          <a href="{% url 'accounts_app:login' %}" class="custom-btn me-2">Login</a>
          <a href="{% url 'accounts_app:register' %}" class="custom-btn">Register</a>
        {% endif %}
      </div>
    </div>
  </div>
  <!-- End Top Bar -->

  <div class="branding d-flex align-items-center">
    <div class="container position-relative d-flex align-items-center justify-content-between">
      <a href="{% url 'del_app:home' %}" class="logo d-flex align-items-center">
        <h1 class="sitename">Dinereserve</h1>
      </a>

      <nav id="navmenu" class="navmenu">
        <ul>
          <li><a href="{% url 'del_app:home' %}" class="{% if request.path == '/' %} active {% endif %}">Home</a></li>
          <li><a href="{% url 'del_app:about' %}" class="{% if request.path == '/about/' %} active {% endif %}">About</a></li>
          <li><a href="{% url 'del_app:menu' %}" class="{% if request.path == '/menu/' %} active {% endif %}">Menu</a></li>
          <li><a href="{% url 'del_app:events' %}" class="{% if request.path == '/events/' %} active {% endif %}">Events</a></li>
          <li><a href="{% url 'del_app:gallery' %}" class="{% if request.path == '/gallery/' %} active {% endif %}">Gallery</a></li>

          <li class="dropdown">
            <a href="#"><span>Contact</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              {% if user.is_authenticated %}
                {% if user.is_superuser %}
                  <li><a href="{% url 'del_app:show_contacts' %}">All messages</a></li>
                {% else %}
                  <li><a href="{% url 'del_app:contact' %}">Contact Us</a></li>
                {% endif %}
              {% endif %}
            </ul>
          </li>

          <li class="dropdown">
            <a href="#"><span>Booking</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
            <ul>
              {% if user.is_authenticated %}
                {% if user.is_superuser %}
                  <li><a href="{% url 'del_app:show_bookings' %}">All Bookings</a></li>
                {% else %}
                  <li><a href="{% url 'del_app:book_table' %}">Book a Table</a></li>
                  <li><a href="{% url 'del_app:show_bookings' %}">My Bookings</a></li>
                {% endif %}
              {% endif %}
            </ul>
          </li>
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>
    </div>
  </div>

</header>

<script>
    function confirmLogout() {
        return confirm('Are you sure you want to logout?');
    }
</script>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}

{% if messages %}
<ul>
  {% for message in messages %} 
  <li style="color: {% if message.tags == 'error' %}red{% else %}#ffb03b{% endif %};
   background-color: {% if message.tags == 'error' %} #433f39 {% else %} #433f39 {% endif %};">
    {{ message }}
  </li>
  {% endfor %}
</ul>

{% endif %}
    <!-- Hero Section -->
    <section id="hero" class="hero section dark-background">

        <div id="hero-carousel" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="5000">
  
          <div class="carousel-item active">
            <img src="{% static 'assets/img/hero-carousel/Hero-1.jpg'%}" alt="">
            <div class="carousel-container">
              <h2><span>DineReserve</span> Restaurant</h2>
              <p>DineReserve is your ultimate dining companion, offering an exceptional culinary experience tailored to delight every guest. With a focus on quality, ambiance, and top-tier service, we provide an ideal setting for family gatherings, romantic dinners, and celebrations. Our diverse menu features a blend of local and international flavors, crafted with the finest ingredients to ensure every bite is memorable.</p>
              <div>
                <a href="{% url 'del_app:menu'%}" class="btn-get-started">Our Menu</a>
                <a href="{% url 'del_app:book_table'%}" class="btn-get-started">Book a table</a>
              </div>
            </div>
          </div><!-- End Carousel Item -->
  
          <div class="carousel-item">
            <img src="{% static 'assets/img/hero-carousel/Hero-2.jpg'%}" alt="">
            <div class="carousel-container">
              <h2>Discover DineReserve</h2>
              <p>DineReserve combines convenience and culinary excellence, allowing you to book tables online, select your preferred seating, and receive instant confirmations. We cater to special requests, ensuring a personalized dining experience. Located in Nairobi, we offer a unique blend of local and international cuisines, crafted to satisfy diverse tastes.</p>
              <div>
                <a href="{% url 'del_app:menu'%}" class="btn-get-started">Our Menu</a>
                <a href="{% url 'del_app:book_table'%}" class="btn-get-started">Book a table</a>
              </div>
            </div>
          </div><!-- End Carousel Item -->
  
          <div class="carousel-item">
            <img src="{% static 'assets/img/hero-carousel/Hero-3.jpg'%}" alt="">
            <div class="carousel-container">
              <h2>Dining Excellence Awaits</h2>
              <p>DineReserve offers seamless online reservations, personalized seating, and instant confirmations. Enjoy our diverse menu of local and international cuisines, designed to delight your taste buds. Experience exceptional dining in Nairobi with us.</p>
              <div>
                <a href="{% url 'del_app:menu'%}" class="btn-get-started">Our Menu</a>
                <a href="{% url 'del_app:book_table'%}" class="btn-get-started">Book a table</a>
              </div>
            </div>
          </div><!-- End Carousel Item -->
  
          <a class="carousel-control-prev" href="#hero-carousel" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
          </a>
  
          <a class="carousel-control-next" href="#hero-carousel" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
          </a>
  
          <ol class="carousel-indicators"></ol>
  
        </div>
  
    </section>
    <!-- /Hero Section -->

{% endblock%}

templates/pay.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Payments{% endblock %}
{% block content %}
<section id="Make payment" class="Make payment section">

  <!-- Section Title -->
  <div class="container section-title" data-aos="fade-up">
    <h2>Make payment</h2>
    <div><span>Make </span> <span class="description-title">Payments.</span></div>
  </div>
  <!-- End Section Title -->


<h2>Make a Payment</h2>

<form method="post" action="{% url 'del_app:stk' %}">
  {% csrf_token %}
    <label class="form-label" for="phone">Phone Number :</label>
    <input type="text" id="phone" name="phone" value="254" placeholder="254" oninput="enforcePrefix()">
    <br><br>

    <label class="form-label" for="amount">Amount :</label>
    <input type="text" id="amount" name="amount" placeholder="Amount">

    <br><br>
  <button type="submit" class="btn btn-dark btn-lg">Submit</button>
</form>
{% endblock %}

templates/show_bookings.html
{% extends 'base.html' %}
{% block title %}Show Bookings{% endblock %}

{% block content %}
    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
        <h2>Your Booking</h2>
        <div><span>Here are Your</span> <span class="description-title">Bookings</span></div>
    </div>
    <!-- End Section Title -->

    <table class="table table-light table-responsive">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Date</th>
                <th>Time</th>
                <th>People</th>
                <th>Message</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for booking in bookings %}
            <tr>
                <td>{{ booking.name }}</td>
                <td>{{ booking.email }}</td>
                <td>{{ booking.phone }}</td>
                <td>{{ booking.date }}</td>
                <td>{{ booking.time }}</td>
                <td>{{ booking.people }}</td>
                <td>{{ booking.message }}</td>
                <td>
                    <a href="{% url 'del_app:edit_booking' booking.id %}" class="btn btn-dark">Edit</a>
                    {% if user.is_superuser %}
                        <form action="{% url 'del_app:delete_booking' booking.id %}" method="post" onsubmit="return confirmDelete()">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    {% else %}
                        <form action="{% url 'del_app:delete_booking' booking.id %}" method="post" onsubmit="return confirmDelete()">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                        <a href="{% url 'del_app:pay' %}" class="btn btn-success">Pay</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        function confirmDelete() {
            return confirm('Are you sure you want to delete this booking?');
        }
    </script>

{% endblock %}

templates/show_contacts.html
{% extends 'base.html' %}
{% block title %}Show contacts{% endblock %}

{% block content %}

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
        <h2>Your contact messages</h2>
        <div><span>show </span> <span class="description-title">contacts</span></div>
    </div>
    <!-- End Section Title -->
<table class="table table-light table-responsive">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Subject</th>
            <th>Message</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for contact in contacts %}
        <tr>

            <td>{{ contact.name }}</td>
            <td>{{ contact.email }}</td>
            <td>{{ contact.subject }}</td>
            <td>{{ contact.message }}</td>
            <td>
                <a href="{% url 'del_app:update_contact' contact.id %}" class="btn btn-dark">Edit</a>
                <a href="{% url 'del_app:delete_contact' contact.id %}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}